### ISSUE TITLE
Dependencies outdated

### ISSUE THREAD

**Issue by ashnur** [graphql/swapi-graphql#10]
Is there a plan maybe for dependencies - most notably babel - to be updated?

**Comment by leebyron** [comment]
Yes, I plan on updating all of GraphQL's projects to Babel6 as soon as the babel-eslint issues have been resolved.

**Comment by wincent** [comment]
Resolved by https://github.com/graphql/swapi-graphql/commit/97eba90b1990ccb88d01b97d626b5355f61a2555
