### ISSUE TITLE
Open API to other origins

### ISSUE THREAD

**Issue by IcanDivideBy0** [graphql/swapi-graphql#11]
Hello,

Do you think it would be ok to add a header `Access-Control-Allow-Origin: *` ?
It might allow other GraphQL projects to use the same graph for example purposes.

**Comment by leebyron** [comment]
I would be happy to entertain a PR for that

**Comment by wincent** [comment]
I left a comment on the related PR (#13):

> Thanks for this, @IcanDivideBy0. Sorry for the slow response.
>
> We had this on ice for a while knowing that we were going to have to move away from Parse due to the Parse shutdown. We are no longer running Express, but instead have an entirely static copy of the app running out of GitHub pages (which incidentally *does* allow cross-origin requests, because it returns a `Access-Control-Allow-Origin: *` header).
>
> I'm going to close this for now because it no longer applies cleanly, and also because we no longer expose a `/graphql` endpoint, which was the initial motivating requirement for this PR and the related issue #11. If you still think that cross-origin requests would be a useful thing for people who might be running Express instances of their own (which you still can, with `npm run start`), then please feel welcome to submit a new PR based off of current master (the main thing which has changed since you made this is that the server `main.js` file has moved from `src/cloud/` to `src/server/`).

So closing this issue now too, but feel free to comment if you think this is in error.
