### ISSUE TITLE
Migrate live demo away from Parse

### ISSUE THREAD

**Issue by leebyron** [graphql/swapi-graphql#12]
We should either wrap this demo up to be browser-contained and run from gh-pages, or deploy to heroku or something since Parse is shutting down in the future.

**Comment by wincent** [comment]
I forgot to link back to this issue in the PRs, but this is now done. We have [a script for making a static (serverless) build of the app](https://github.com/graphql/swapi-graphql/blob/127d1d3c402c97c2db9673129dcf5a60a67228f7/scripts/build-public) and [another for deploying it via the `gh-pages` branch](https://github.com/graphql/swapi-graphql/blob/127d1d3c402c97c2db9673129dcf5a60a67228f7/scripts/deploy-public). Build sources can be found [in the "public" directory](https://github.com/graphql/swapi-graphql/tree/127d1d3c402c97c2db9673129dcf5a60a67228f7/src/public).
