### ISSUE TITLE
Queries in the live demo site seem to give incorrect results

### ISSUE THREAD

**Issue by PeterSulcs** [graphql/swapi-graphql#120]
I may be missing something, but in attempting to do joins based on films and vehicle connections I get duplicate vehicles. Is the demo implementation incorrect or is my query syntax incorrect?

```
{
  allFilms(first: 3) {
    films {
      title
      vehicleConnection {
        vehicles {
          id
          name
        }
      }
    }
  }
}
```
[Link to live demo with query populated](http://graphql.org/swapi-graphql/?query=%7B%0A%20%20allFilms(first%3A%201)%20%7B%0A%20%20%20%20films%20%7B%0A%20%20%20%20%20%20title%0A%20%20%20%20%20%20vehicleConnection%20%7B%0A%20%20%20%20%20%20%20%20vehicles%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20filmConnection%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20films%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%09%0A%20%20%7D%0A%7D%0A)

The result lists the same vehicle multiple times within a single movie:
```
{
  "data": {
    "allFilms": {
      "films": [
        {
          "title": "A New Hope",
          "vehicleConnection": {
            "vehicles": [
              {
                "id": "dmVoaWNsZXM6NA==",
                "name": "Sand Crawler"
              },
              {
                "id": "dmVoaWNsZXM6Ng==",
                "name": "T-16 skyhopper"
              },
              {
                "id": "dmVoaWNsZXM6Nw==",
                "name": "X-34 landspeeder"
              },
              {
                "id": "dmVoaWNsZXM6OA==",
                "name": "TIE/LN starfighter"
              },
              {
                "id": "dmVoaWNsZXM6NA==",
                "name": "Sand Crawler"
              },
              {
                "id": "dmVoaWNsZXM6Ng==",
                "name": "T-16 skyhopper"
              }, ...
```

Am I missing something?

**Note:** This links to a closed issue because I realized this was the repo for the Star Wars GraphQL wrapper around swapi.org used in the demo site and so moved my issue here. I still can't make sense of the result I am getting.

**Comment by PeterSulcs** [comment]
After cloning and running locally, the caching mechanism itself seems to be causing the issue, the swapi-graphql/src/api/cachedData/[cachedData.js] file includes the same duplicate vehicles issue.

**Comment by wincent** [comment]
Thanks for the report @PeterSulcs. Looks like a long-standing bug.

**Comment by wincent** [comment]
I believe this is now fixed (also deployed to the site: [example query](http://graphql.org/swapi-graphql/?query=%7B%0A%20%20allFilms%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20vehicleConnection%20%7B%0A%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20node%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) via https://github.com/graphql/swapi-graphql/commit/9e90ff64f282a1f0e93d29afcc5dba06c239f2c5).
