### ISSUE TITLE
Error while running npm test

### ISSUE THREAD

**Issue by programmerKaustubh** [graphql/swapi-graphql#126]
C:\swapi-graphql-master\scripts\pretty.js:36
const out = stdout.toString().trim();
                   ^

TypeError: Cannot read property 'toString' of null
    at Object.<anonymous> (C:\swapi-graphql-master\scripts\pretty.js:36:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swapi-graphql@ pretty-check: `node scripts/pretty.js --check`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swapi-graphql@ pretty-check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kmema\AppData\Roaming\npm-cache\_logs\2017-11-13T03_07_21_469Z-debug.log
npm ERR! Test failed.  See above for more details.

**I am learning how to use GraphQL and connect with my android Application. But I am getting an error on npm test command. Am I supposed to run this command in any specific folder. And also I another issue with creating Schema.json file for my android app for variant debug purpose**

**Comment by IvanGoncharov** [comment]
@programmerKaustubh Sorry for the delay.
It should be already fixed since I replaced custom prettier.js script with `eslint-pluggin-prettier`.
Would be great if you try `npm test` on latest master and report issues if any.
