### ISSUE TITLE
Expose API for outside testing

### ISSUE THREAD

**Issue by deinok** [graphql/swapi-graphql#127]
Could you expose the API without the GraphiQL interface?

So other people can send requests to the SWAPI GraphQL endpoint in order to tests GraphQL Clients.

- [ ] GET
- [ ] POST

**Comment by IvanGoncharov** [comment]
@deinok I added `Deploy to Heroku` button so it's very easy to spin up your own server with a couple of clicks and free of charge. You need to create an account on Heroku but this is also very simple and you can do this without a credit card.
