### ISSUE TITLE
Endpoint to get GraphQL Schema using a GraphQL Client

### ISSUE THREAD

**Issue by gabsprates** [graphql/swapi-graphql#138]
Hi, there is a way, a public endpoint, to get this GraphQL Schema using Relay or Apollo (or another client)?

**Comment by IvanGoncharov** [comment]
Hi @gabsprates and sorry for the delay.
You can one click (+free of charge) run your own instance on Heroku or now.sh just click the button in README.

**Comment by gabsprates** [comment]
Thanks @IvanGoncharov.

I was setting up wrong my `.graphqlconfig` (🙈), it works now. Thanks
