### ISSUE TITLE
Password Expired

### ISSUE THREAD

**Issue by tonygledhill** [graphql/swapi-graphql#140]
When you try and run as query on http://swapi.graphene-python.org/graphql. You get the following message.

"message": "(1862, 'Your password has expired. To log in you must change it using a client that supports expired passwords.')",

**Comment by IvanGoncharov** [comment]
@tonygledhill Repo API that you are referring to is 
https://github.com/graphql-python/swapi-graphene
Please report it there.
This version of SWAPI is hosted as https://graphql.github.io/swapi-graphql/
