### ISSUE TITLE
Error while starting the server on Windows

### ISSUE THREAD

**Issue by yashpalsingh8** [graphql/swapi-graphql#16]
Tell the author that this fails on your system:
npm ERR!     if [ ! -f src/api/cachedData/cache.js ]; then echo 'Downloading cache...' && node src/api/cachedData/downloadCache.js > src/api/cachedData/cache.js && echo 'Cached!'; fi;

This is the error I am getting on my command prompt while starting the server, Kindly provide your help to resolve the issue.

**Comment by avinashdudi** [comment]
I got the same error, were you able to resolve.

**Comment by Magneticmagnum** [comment]
Same here :(
Windows machine, node version 6.9.1

**Comment by wincent** [comment]
Not clear if everybody on this thread is using Windows, but if that is the case then I believe this should be fixed by #27 (although that does need a rebase).

**Comment by wincent** [comment]
Actually, looking more closely, I see that #27 (and #42) only address `npm run download`, not `npm run start`. Any Windows users out there care to work through any remaining issues and submit a PR?

**Comment by xgqfrms-gildata** [comment]
# solution

```json
"scripts": {
    "download-shell-bug": "sh scripts/download",
    "download": "babel-node src/api/cachedData/downloadCache.js > src/api/cachedData/cache.js",
}
```

https://github.com/graphql/swapi-graphql/pull/131/commits/d13c1b0a36c73030a3d2639290f2dcace2d098fd

**Comment by IvanGoncharov** [comment]
@yashpalsingh8 @arbitdudi @Magneticmagnum @xgqfrms-gildata It should be fixed on latest master.
Can you please try and report if it works on Windows?
Note: you need to run `npm install` or `yarn` first.

**Comment by tzkmx** [comment]
It works on Windows, I've just tested it when merging the changes in master to rework the proposal for a build-public script based in node, instead of bash.: #133

**Comment by IvanGoncharov** [comment]
@tzkmx Thanks for testing it.
Both `npm run download` and `npm run build-public` should now work on Windows so I close this issue. But feel free to open separate issues if you have any other windows-related problems.
