### ISSUE TITLE
API unusable with recent graphql client

### ISSUE THREAD

**Issue by sedubois** [graphql/swapi-graphql#19]
Hi! Similar to what I [reported](https://github.com/clayallsopp/graphqlhub/issues/37) in GraphQLHub, any client using graphql 0.5.0 or later is incompatible with this server. Do you intend to upgrade it? Right now, I don't know any public GraphQL API compatible with a recent `graphql` package version (currently `0.7.1`).

**Comment by wincent** [comment]
Thanks for bringing this up. As far as I know we're all up to date now, so I'm going to close this. Please correct me if I'm mistaken!
