### ISSUE TITLE
url text color needs to be brighter

### ISSUE THREAD

**Issue by Marikoikoiko** [graphql/swapi-graphql#217]
Currently the grey color of the url is washed out and should be a brighter color like white

**Comment by vishalsingh2972** [comment]
hey @MarikoIwata can you assign this to me if its still open?

**Comment by MarikoIwata** [comment]
@vishalsingh2972 It is still open, but I don't have the ability to assign. Perhaps reach out to the operations email in the readme?

**Comment by vishalsingh2972** [comment]
@acao @thomasheyenbrock could you assign this to me, would like to work on it!

**Comment by acao** [comment]
@vishalsingh2972 this would need to be fixed in the graphql/graphiql repo, can you open the ticket there?

**Comment by vishalsingh2972** [comment]
Hi @acao I see no issue of "url text color" in the graphql/graphiql repo, should I directly submit a PR there?

**Comment by acao** [comment]
sure!

**Comment by JoviDeCroock** [comment]
As this issue is better tackled on the GraphiQL repository I'll close this for the time being. If we need to do any changes like bumping the package or have the option to fix this on our side, a PR is always welcomed 🙌

**Comment by acao** [comment]
@JoviDeCroock thanks for closing this, the PR was already submitted!
