### ISSUE TITLE
https://graphql.org/swapi-graphql returns 404

### ISSUE THREAD

**Issue by jmartisk** [graphql/swapi-graphql#219]
The UI at https://graphql.org/swapi-graphql doesn't seem to work anymore. Is it ever coming back?

**Comment by vishalsingh2972** [comment]
@jmartisk can you assign this to me if its open, wanna give it a try!

**Comment by jmartisk** [comment]
@vishalsingh2972 unfortunately no I don't have any permissions in this repo, so I can't assign. I think we need an admin to have a look what happened to the deployment, but I don't know where to find the appropriate person.

**Comment by benjie** [comment]
@jorydotcom This seems like a significant issue - we've lots the SWAPI example API!

**Comment by acao** [comment]
we are tracking the issue here

https://github.com/graphql/graphql.github.io/issues/1427

it seems in the migration from netlify, we overlooked the redirects I set up for this. I will contact jory today!

**Comment by benjie** [comment]
This is now resolved: https://graphql.org/swapi-graphql/
