### ISSUE TITLE
https://graphql.org/swapi-graphql is not working? 

### ISSUE THREAD

**Issue by soggybag** [graphql/swapi-graphql#226]
Looks like this https://graphql.org/swapi-graphql is not working any more?

**Comment by mstralka** [comment]
When I try to load `https://graphql.org/swapi-graphql/` in The GraphiQL chrome extension, I get this error message:
~~~json
{
  "errors": [
    {
      "message": "Unexpected end of JSON input",
      "stack": "SyntaxError: Unexpected end of JSON input\n    at chrome-extension://jhbedfdjpmemmbghfecnaeeiokonjclb/dist/index.js:325:17379"
    }
  ]
}
~~~

**Comment by acao** [comment]
closing for https://github.com/graphql/graphql.github.io/issues/1618 since there is nothing we can do here
