### ISSUE TITLE
Not required arguments are required.

### ISSUE THREAD

**Issue by iKOPKACtraxa** [graphql/swapi-graphql#227]
There is a problem that several root fields have not required arguments, but if I make a request I got error.
For example: root field "[film](https://swapi-graphql.netlify.app/?query=%7B%0A%20%20film%7B%0A%20%20%20%20%0A%20%20%20%20id%0A%20%20%7D%0A%7D#)" have two arguments:
id: ID
filmID: ID
and both are not required.
If I make a request {film {id}} I'll get error "must provide id or filmID".
It must be something like this "film(id: ID!): Film" in schema.
The same in: person, planet, species, starship, vehicle.

**Comment by JoviDeCroock** [comment]
They aren't required in the schema but they are required in code, https://github.com/graphql/swapi-graphql/blob/master/src/schema/index.js#L59 this was probably before we had control over one or the other required inputs, now with [oneOf](https://github.com/graphql/graphql-js/blob/34a6ed7773dcf1c713b03789f8487fa3154db3ea/website/pages/oneof-input-objects.mdx) we can do this
