### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by wincent** [graphql/swapi-graphql#45]
Some errors of late have only been caught by manually running `npm test` (which runs eslint, flow and the test suite).

**Comment by AGS-** [comment]
#55

**Comment by wincent** [comment]
Ok @AGS-, so I merged your `.travis.yml` and I hit the "Active" checkbox in the settings:

<img width="355" alt="webhook_-_travis_ci" src="https://cloud.githubusercontent.com/assets/7074/22859699/1ce08406-f09a-11e6-908c-9da636ce3bf3.png">

Will see if this works. I suspect we might have to tweak the access token. The other GraphQL projects that work with Travis CI seem to use a different token. Will talk about it with the others in the office on Monday I guess.

**Comment by AGS-** [comment]
Cool, sounds good!

**Comment by wincent** [comment]
It's working. Needed a tweak (#58) but we're green now.
