### ISSUE TITLE
http://graphql-swapi.parseapp.com/ is outdated

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/swapi-graphql#49]
You have an outdated instance of this proxy hosted on:
http://graphql-swapi.parseapp.com/
Can you please update it to the latest version.

Having example GraphQL server helps a lot when you develop tooling for GraphQL.
\+ many developers like to send queries from cURL, Postman, source code, etc.

**Comment by wincent** [comment]
Thanks for bringing this up.

[Parse shut down today](http://blog.parse.com/announcements/a-parse-shutdown-reminder/). A static copy of the app has been migrated to http://graphql.org/swapi-graphql/ and if is anybody interested in experimenting with a dynamic copy, a local Express server can be run with `npm run start`.

**Comment by wincent** [comment]
If you know anybody who's linking to the old URL, please advise them to update it, because it won't be coming back.
