### ISSUE TITLE
GraphiQL doesn't work at http://graphql-swapi.parseapp.com/.

### ISSUE THREAD

**Issue by sulliwane** [graphql/swapi-graphql#5]
I can't use GraphiQL at http://graphql-swapi.parseapp.com/, could it be the same issue I'm experiencing there https://github.com/graphql/express-graphql/issues/34 ?

Thank you!

**Comment by mfunkie** [comment]
I got 'Unexpected end of input' when running this query:

```
query test {
  allFilms {
    edges {
      node {
        id
      }
    } 
  }
}
```

Type and Schema introspection works though.

**Comment by sulliwane** [comment]
I believe it's a problem with firefox, as after switching to Opera or Chrome I could see GraphiQL responses.

Now I have same problem as @mfunkie

**Comment by leebyron** [comment]
Updated to latest version of graphiql and express-graphql which fix this issue! Thanks again for reporting
