### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by zardra** [graphql/swapi-graphql#50]
When attempting to run `npm run download`, I received the following output:

> swapi-graphql@ download /Users/lizborchardt/swapi-graphql
> sh scripts/download
>
> Downloading cache...
> /Users/lizborchardt/swapi-graphql/src/api/cachedData/downloadCache.js:54
>   let url = prefix + urlTypes[type] + '/';
>   ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:974:3
> 
> npm ERR! Darwin 16.4.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "download"
> npm ERR! node v4.6.1
> npm ERR! npm  v2.15.9
> npm ERR! code ELIFECYCLE
> npm ERR! swapi-graphql@ download: `sh scripts/download`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the swapi-graphql@ download script 'sh scripts/download'.
> npm ERR! This is most likely a problem with the swapi-graphql package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     sh scripts/download
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs swapi-graphql
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! 
> npm ERR!     npm owner ls swapi-graphql
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/lizborchardt/swapi-graphql/npm-debug.log

**Comment by wincent** [comment]
What version of `node` are you running? It seems like that you're seeing this because the version you are running is too old to have `let` etc support.

As a workaround, you could try this:

```
node_modules/.bin/babel-node src/api/cachedData/downloadCache.js > src/api/cachedData/cache.js`
```

Which is roughly equivalent to the following, which is what the `download` script is doing:

```
node src/api/cachedData/downloadCache.js > src/api/cachedData/cache.js
```

We should be able to tweak the script to use a built copy of `downloadCache.js` instead of the raw source, so it will work on a wider range of `node` versions.

**Comment by wincent** [comment]
You could also try PR #51 and see if it works.

**Comment by zardra** [comment]
You're right; I'm definitely running an old version of node (4.6.1).  I had something that required that version, and I never updated and hadn't thought to check.

I did manage to get the data by just running `downloadCache.js` directly.
