### ISSUE TITLE
Provide SWAPI as public GraphQL server

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/swapi-graphql#83]
Continuation of #49.
Hosted GraphiQL is a great solution for introducing new users to GraphQL.
However many GraphQL tools designed to work with 3rd-party GraphQL APIs so in order to provide a demo or example they need to host they own server.
For our [GraphQL Fakerl](https://github.com/APIs-guru/graphql-faker) we host SWAPI under https://swapi.apis.guru domain.

Problem is that create a barrier for tooling author since hosting your own server requires time and money investments.

**Comment by wincent** [comment]
Thanks for bringing this up again, @IvanGoncharov. I think the main issue here is that we don't necessarily want to be in the business of providing any kind of hosted GraphQL access, and it is a gap that we'd rather see filled by the community, given that there already quite a few participants out there with varying degrees of investment in the whole subject of onboarding, educating and introducing new users to GraphQL.

Free experimentation is already quite direct (just `npm start run` in this repo). We'd be happy to supplement the README here, and likely also the docs over at graphql.org, with links to hosted solutions provided by third parties. You'd be welcome to submit a PR if you wanted us to link to https://swapi.apis.guru/ for example. For now though I am going to close this one as I don't think that hosting a public server is something that we are going to prioritize and do ourselves at this time.

**Comment by acao** [comment]
Reopened as per discussion with @IvanGoncharov , we will move forward on getting an OSS heroku account for providing this public API example

**Comment by acao** [comment]
closing since we moved to netlify functions!

**Comment by bot19** [comment]
Not sure if this is related but I tried using https://graphql.org/swapi-graphql in a codesandbox, but it didn't seemed to work (not public API?), so I tried @IvanGoncharov https://swapi.apis.guru and it works.

Anyways, does "netlify functions" fix this? How do I hook it up to my codesandbox? I am trying to make a personal demo.

Thanks

**Comment by acao** [comment]
@bot19 that netlify example will reveal the working URL if you know where to look (tip: look at network tab) ;)!

that said, we should have a reverse proxy from a more convenient URL.  I could at least add the temporary URL to the repo!
