### ISSUE TITLE
Enums for episodes?

### ISSUE THREAD

**Issue by kevinSuttle** [graphql/swapi-graphql#9]
Seeing this in the graphql-js repo under tests, but not here. Am I missing where the enums are defined, or are the tests doubling as the schema definition somehow?

https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsSchema.js#L77

**Comment by dschafer** [comment]
The star wars schema in graphql-js is a simplified example schema; it actually is independent from this example repo, which wraps SWAPI. This ended up being confusing, sorry about that!

**Comment by kevinSuttle** [comment]
Ah, I suspected as much. Thanks for clarifying!
